---
# tasks file for nginx_balancer

- name: Install Docker
  include_role:
    name: docker

- name: Enable nginx on Amazon Linux
  shell: amazon-linux-extras enable nginx1

- name: Install nginx for Centos
  yum:
    name:
    - nginx
    state: latest

- name: Start nginx
  service: 
    name: nginx 
    state: started 
    enabled: yes

- name: Generate balancer config file
  template: src=load_balancer.j2 dest=/etc/nginx/nginx.conf

- name: Restart Nginx
  service: 
    name: nginx 
    state: restarted
